name: Tests

on: [push]

jobs:
  hadolint:
    name: Check docker images (Hadolint)
    runs-on: ubuntu-latest
    container: hadolint/hadolint
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Checking image Best Practices
        run: hadolint Dockerfile

  test_unit:
    name: test
    runs-on: ubuntu-lastest
    container: vincentlau77/blog_php
    steps:
      - name: install composer
        run: composer install
      - name: script
        run: bin/phpunit
